local hex = require("libraries/hexagon/hexagon")

-- Main:
-- add autosave
-- change cursor when input field selected
-- read input field
-- show saved path in input field


--Aditional:
-- prepare drag cursor in tiff format 
-- load drag cursor

-- Bugs:

function init(self)
   msg.post("/camera", "acquire_input_focus")
   msg.post("/main#artist", "acquire_input_focus")
   hex.size = 76.8 * 0.5
   
end

function update(self)
   
end